apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
  namespace: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs 
    spec:
      containers:
      - name: nodejs-hello-world
        image: tarun/node-hello-world
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  namespace: nodejs
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: nodejs
